version: '3'

services:
  app:
    image: clojure:openjdk-8-lein-alpine
    volumes:
      - ".:/var/www/"
    ports:
      - "8080:8080"
    working_dir: /var/www
    links:
      - mongodb
    depends_on:
      - mongodb
    command: lein run
  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports: 
      - 27017:27017
    volumes:
      - ./data/db:/data/db

